<style type="text/css">
h1.title {
  text-align: center;
}
</style>
---
title: Tej Malepati
output: html_document
runtime: shiny
---
<table>
<tr><td>
I am a NoSQL Leader, Author and SME with expertise in designing, building, and maintaining Database products along with its strategic vision and roadmaps being on par with the latest technological trends with 11+ years of IT experience. Specialized in automated cloud deployments and maintaining highly scalable live Cassandra, JanusGraph, MongoDB, Elasticsearch and Redis database clusters using RPMs, Docker, LOCI, Vela, Rundeck, Kubernetes, Helm, Drone, Spinnaker and Ansible.

Built:

* Real time data streaming framewrok from Cassandra to Hadoop using Kafka and Apache Storm for analytics.
* Framework for validating Data consistency between 2 databases.

Refer **[LinkedIn](https://linkedin.com/in/tmalepati)** for further information.
</td><td align='center'>
Technical Skill Set
```{r eval=T, echo=F, message=F}
library(dplyr)
library(wordcloud)
p = as.data.frame(installed.packages()[,c(1)])
colnames(p) = c('name')
p = p %>%
  mutate(size = ifelse(name %in% c('caret','broom','dplyr','tidyr','randomForest','wordcloud','gapminder','purrr','stats','rmarkdown','knitr','shiny'), 25, 9))

name = c('Cassandra','JanusGraph','Weaviate','Grafana','Kibana','MongoDB','Elasticsearch','Redis','R','Spark','Python','Oracle','MySQL','Jupyter','Rundeck','Consul','InfluxDB','Mesos','Marathon','Chronos','Sensu','JMX Trans','OpsCenter','Chef','Bash','HTML5','CSS3')
size = c(36,35,35,35,35,35,32,32,32,32,32,30,30,30,30,27,27,1,1,1,1,1,1,1,1,1,1)

p = rbind(p, data.frame(name,size))
wordcloud(p$name,p$size, max.words = Inf, random.order = F, scale=c(3,.1), colors = brewer.pal(8,"Dark2"), rot.per = .3)
```
</td></tr>
</table>
